services:
  sveltekit-landing:
    image: ${LANDING_IMAGE}
    container_name: sveltekit-landing
    ports:
      - "${LANDING_EXTERNAL_PORT}:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      ORIGIN: ${LANDING_ORIGIN}
    restart: unless-stopped

  sveltekit-catalog:
    image: ${CATALOG_IMAGE}
    container_name: sveltekit-catalog
    ports:
      - "${CATALOG_EXTERNAL_PORT}:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      ORIGIN: ${CATALOG_ORIGIN}
    restart: unless-stopped
